

#define DFI_TX_HEADER \
    { 0x44, 0x66, 0x54, 0x78}

enum DfiCustomTxType {
    None = 0,
    Reject = 1,
    CreateMasternode = 'C',
    ResignMasternode = 'R',
    UpdateMasternode = 'm',
    CreateToken = 'T',
    MintToken = 'M',
    BurnToken = 'F',
    UpdateToken = 'N',
    UpdateTokenAny = 'n',
    CreatePoolPair = 'p',
    UpdatePoolPair = 'u',
    PoolSwap = 's',
    PoolSwapV2 = 'i',
    AddPoolLiquidity = 'l',
    RemovePoolLiquidity = 'r',
    UtxosToAccount = 'U',
    AccountToUtxos = 'b',
    AccountToAccount = 'B',
    AnyAccountsToAccounts = 'a',
    SmartContract = 'K',
    FutureSwap = 'Q',
    SetGovVariable = 'G',
    SetGovVariableHeight = 'j',
    AutoAuthPrep = 'A',
    AppointOracle = 'o',
    RemoveOracleAppoint = 'h',
    UpdateOracleAppoint = 't',
    SetOracleData = 'y',
    ICXCreateOrder = '1',
    ICXMakeOffer = '2',
    ICXSubmitDFCHTLC = '3',
    ICXSubmitEXTHTLC = '4',
    ICXClaimDFCHTLC = '5',
    ICXCloseOrder = '6',
    ICXCloseOffer = '7',
    SetLoanCollateralToken = 'c',
    SetLoanToken = 'g',
    UpdateLoanToken = 'x',
    LoanScheme = 'L',
    DefaultLoanScheme = 'd',
    DestroyLoanScheme = 'D',
    Vault = 'V',
    CloseVault = 'e',
    UpdateVault = 'v',
    DepositToVault = 'S',
    WithdrawFromVault = 'J',
    PaybackWithCollateral = 'W',
    TakeLoan = 'X',
    PaybackLoan = 'H',
    PaybackLoanV2 = 'k',
    AuctionBid = 'I',
    FutureSwapExecution = 'q',
    FutureSwapRefund = 'w',
    TokenSplit = 'P',
    CreateCfp = 'z',
    Vote = 'O',
    CreateVoc = 'E',
    ProposalFeeRedistribution = 'Y',
    UnsetGovVariable = 'Z'
};

int get_dfi_tx_type(const uint8_t script[],
                    size_t script_len,
                    char *out,
                    size_t out_len,
                    uint64_t *amount,
                    global_context_t *G_coin_config);