name: Build custom speculos-defichain image

on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/builder-image-workflow.yml
      - .github/workflows/Dockerfile

jobs:
  build:
    name: Build and push ledger-app-builder image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Build and push speculos-defichain to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        dockerfile: .github/workflows/Dockerfile
        repository: Jellywallet/ledger-app-defichain/speculos-defichain
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_sha: true
        tags: latest